Boa noite!

 Para executar a célula clica em chift + enter

In [ ]:
#celular de código
# guardar 2 na variável x
x = 2

In [ ]:

# para ver o valor de x
x

2

##Execuçao célula a célula.

- Número inteiro (2) exige menos armazenamento na memória.
- Número float (2.0) exige mais armazenamento na memória.

In [ ]:
#número float atribuir valor a variavel y
y = 2.0

In [ ]:
#mostrar o valor de y
y

2.0

In [ ]:
#variável tipo texto
texto = "aula"

In [ ]:
texto

'aula'

## Exemplos Práticos: Olá, Mundo!

In [ ]:
print(" Olá, Mundo!")

 Olá, Mundo!


## Menos código para operações simples

In [ ]:
#listas
numeros = [1,2,3]

In [ ]:
#mostrar a lista numeros
numeros

[1, 2, 3]

In [ ]:
#somar os números da lista
#usar a função sum() para somar os números da lista
#pode usar o print() para mostrar ou usar a função sum() direto
print(sum(numeros))

6


In [ ]:
#usar a função sum()
sum(numeros)

6

In [ ]:
#Alturas
alturas = [170,180,160,165,158]

In [ ]:
sum(alturas)

833

In [ ]:
alturas * 10

array([1700, 1800, 1600, 1650, 1580])

##Biblioteca para analise eficiente

In [ ]:
#para importar a biblioteca pandas
#O panda é  como se fosse o excel dentro do python
#O objeto é o dataframe e como se fosse a tabela do excel
# import pandas com a sigla pd
import pandas as pd

In [ ]:
#criando o dataframe
df = pd.DataFrame({"Produto": ["A", "B", "C"], "Vendas": [10, 20, 15]})

In [ ]:
#visualizar o dataframe
df

Produto  Vendas
0       A      10
1       B      20
2       C      15

from matplotlib import pyplot as plt
df['Vendas'].plot(kind='hist', bins=20, title='Vendas')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
df.groupby('Produto').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df['Vendas'].plot(kind='line', figsize=(8, 4), title='Vendas')
plt.gca().spines[['top', 'right']].set_visible(False)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(df['Produto'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df, x='Vendas', y='Produto', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [ ]:
# Bibloteca numpy para realizar operações
#objeto é chamado de array que em portuguê é  vetor
import numpy as np


In [ ]:
arr = np.array([1,2,3,4])
print(arr * 10)

[10 20 30 40]


In [ ]:
arr * 10

array([10, 20, 30, 40])

In [ ]:
#para transformar altura em uma array
alturas = np.array([170,180,160,165,158])

In [ ]:
#para mostrar a média das alturas
np.mean(alturas)

np.float64(166.6)

##Usando o Goglee Colab

 **Isso é Destaque!**
 - Listas,anotações e explicações ficam junto do código.



## Função Print() e Sintxe Básica

In [ ]:
#
nome = "Lucas"
idade = 22
print("Nome:",nome,"Idade:", idade)

Nome: Lucas Idade: 22


##Definindo sua propria função

In [ ]:
#função def
# pode colocar vários comandos
def saudacao(nome):#parametro da função saudação
  print("Bem vindo," ,nome)
  print("Benevuto", nome)

In [ ]:
#chamar a função
saudacao("Maria") #argumento é o nome Maria

Bem vindo, Maria
Benevuto Maria


##Indentação

- Tab do teclado

In [ ]:
#clica no tab do teclado para deixar o print dentro

def saudacao(nome):
  print("Bem vindo," ,nome)
  print("Benevuto", nome)